// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Demo.Data.Models
{
    public partial class Order
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public int CustomerId { get; set; }
        public DateTime Time { get; set; }
        public double TotalPrice { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }

        public virtual Account Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}